package com.taller.proyectofinalcomponentes.core.localization

data class AppStrings(
    val appSubtitle: String,
    val loginTitle: String,
    val loginSubtitle: String,
    val email: String,
    val password: String,
    val buyer: String,
    val seller: String,
    val selectAccountType: String,
    val loginButton: String,
    val logout: String,
    val home: String,
    val search: String,
    val wishlist: String,
    val profile: String,
    val homeGreeting: String,
    val sellerGreeting: String,
    val searchProducts: String,
    val categories: String,
    val seeAll: String,
    val flashSale: String,
    val flashSaleDescription: String,
    val limitedTime: String,
    val featuredProducts: String,
    val cart: String,
    val clear: String,
    val emptyCart: String,
    val emptyCartDescription: String,
    val continueShopping: String,
    val orderSummary: String,
    val checkout: String,
    val back: String,
    val productDetail: String,
    val description: String,
    val quantity: String,
    val addToCart: String,
    val addedToCart: String,
    val notifications: String,
    val language: String,
    val english: String,
    val spanish: String,
    val promotionTitle: String,
    val promotionBody: String,
    val cartNotificationTitle: String,
    val cartNotificationBody: String,
    val orderNotificationTitle: String,
    val orderNotificationBody: String,
    val items: String,
    val results: String,
    val addProduct: String,
    val productName: String,
    val productDescription: String,
    val priceCop: String,
    val oldPriceCop: String,
    val category: String,
    val saveProduct: String,
    val productCreated: String,
    val sellerPanel: String,
    val sellerProducts: String,
    val electronics: String,
    val fashion: String,
    val homeCategory: String,
    val beauty: String,
    val sports: String,
    val food: String,
    val orderPlaced: String,
    val orderConfirmed: String,
    val placeOrder: String,
    val reviewOrder: String,
    val continueText: String,
    val address: String,
    val paymentMethod: String,
    val secureCheckout: String,
    val purchases: String,
    val sales: String,
    val purchaseHistory: String,
    val salesHistory: String,
    val noPurchases: String,
    val noSales: String,
    val totalSold: String
)

fun strings(language: AppLanguage): AppStrings = when (language) {
    AppLanguage.Spanish -> AppStrings(
        appSubtitle = "Aplicación Android de comercio electrónico",
        loginTitle = "Iniciar sesión",
        loginSubtitle = "Accede a tu cuenta",
        email = "Correo",
        password = "Contraseña",
        buyer = "Comprador",
        seller = "Vendedor",
        selectAccountType = "Selecciona el tipo de cuenta",
        loginButton = "Ingresar",
        logout = "Cerrar sesión",
        home = "Inicio",
        search = "Buscar",
        wishlist = "Favoritos",
        profile = "Perfil",
        homeGreeting = "¡Bienvenido de nuevo!",
        sellerGreeting = "Panel para gestionar productos",
        searchProducts = "Buscar productos...",
        categories = "Categorías",
        seeAll = "Ver todo",
        flashSale = "Oferta relámpago ⚡",
        flashSaleDescription = "Hasta 40% de descuento en productos seleccionados",
        limitedTime = "Oferta por tiempo limitado",
        featuredProducts = "Productos destacados",
        cart = "Carrito",
        clear = "Limpiar",
        emptyCart = "Tu carrito está vacío",
        emptyCartDescription = "Agrega productos para comenzar",
        continueShopping = "Continuar comprando",
        orderSummary = "Resumen del pedido",
        checkout = "Finalizar compra",
        back = "Atrás",
        productDetail = "Detalle del producto",
        description = "Descripción",
        quantity = "Cantidad",
        addToCart = "Agregar al carrito",
        addedToCart = "¡Agregado!",
        notifications = "Notificaciones",
        language = "Idioma",
        english = "Inglés",
        spanish = "Español",
        promotionTitle = "Promoción ShopWave",
        promotionBody = "Revisa las ofertas disponibles en productos seleccionados.",
        cartNotificationTitle = "Producto agregado",
        cartNotificationBody = "El producto se agregó correctamente al carrito.",
        orderNotificationTitle = "Pedido confirmado",
        orderNotificationBody = "Tu pedido fue registrado correctamente.",
        items = "productos",
        results = "resultados",
        addProduct = "Agregar producto",
        productName = "Nombre del producto",
        productDescription = "Descripción del producto",
        priceCop = "Precio en pesos colombianos",
        oldPriceCop = "Precio anterior opcional",
        category = "Categoría",
        saveProduct = "Guardar producto",
        productCreated = "Producto creado y visible para compradores",
        sellerPanel = "Panel de vendedor",
        sellerProducts = "Productos publicados",
        electronics = "Electrónica",
        fashion = "Moda",
        homeCategory = "Hogar",
        beauty = "Belleza",
        sports = "Deportes",
        food = "Comida",
        orderPlaced = "¡Pedido realizado!",
        orderConfirmed = "Tu pedido fue confirmado y será entregado pronto.",
        placeOrder = "Realizar pedido 🔒",
        reviewOrder = "Revisar pedido",
        continueText = "Continuar",
        address = "Dirección de entrega",
        paymentMethod = "Método de pago",
        secureCheckout = "Pago seguro",
        purchases = "Compras",
        sales = "Ventas",
        purchaseHistory = "Historial de compras",
        salesHistory = "Registro de ventas",
        noPurchases = "Aún no tienes compras registradas",
        noSales = "Aún no hay ventas registradas",
        totalSold = "Total vendido"
    )

    AppLanguage.English -> AppStrings(
        appSubtitle = "Android E-Commerce App",
        loginTitle = "Login",
        loginSubtitle = "Access your account",
        email = "Email",
        password = "Password",
        buyer = "Buyer",
        seller = "Seller",
        selectAccountType = "Select account type",
        loginButton = "Login",
        logout = "Log out",
        home = "Home",
        search = "Search",
        wishlist = "Wishlist",
        profile = "Profile",
        homeGreeting = "Welcome back!",
        sellerGreeting = "Panel to manage products",
        searchProducts = "Search products...",
        categories = "Categories",
        seeAll = "See all",
        flashSale = "Flash Sale ⚡",
        flashSaleDescription = "Up to 40% off on selected products",
        limitedTime = "Limited time offer",
        featuredProducts = "Featured Products",
        cart = "Cart",
        clear = "Clear",
        emptyCart = "Your cart is empty",
        emptyCartDescription = "Add products to get started",
        continueShopping = "Continue Shopping",
        orderSummary = "Order Summary",
        checkout = "Checkout",
        back = "Back",
        productDetail = "Product Detail",
        description = "Description",
        quantity = "Quantity",
        addToCart = "Add to Cart",
        addedToCart = "Added to Cart!",
        notifications = "Notifications",
        language = "Language",
        english = "English",
        spanish = "Spanish",
        promotionTitle = "ShopWave Promotion",
        promotionBody = "Check the current deals on selected products.",
        cartNotificationTitle = "Product added",
        cartNotificationBody = "The product was added to the cart successfully.",
        orderNotificationTitle = "Order confirmed",
        orderNotificationBody = "Your order was placed successfully.",
        items = "items",
        results = "results",
        addProduct = "Add product",
        productName = "Product name",
        productDescription = "Product description",
        priceCop = "Price in Colombian pesos",
        oldPriceCop = "Previous price optional",
        category = "Category",
        saveProduct = "Save product",
        productCreated = "Product created and visible to buyers",
        sellerPanel = "Seller panel",
        sellerProducts = "Published products",
        electronics = "Electronics",
        fashion = "Fashion",
        homeCategory = "Home",
        beauty = "Beauty",
        sports = "Sports",
        food = "Food",
        orderPlaced = "Order placed!",
        orderConfirmed = "Your order has been confirmed and will be delivered soon.",
        placeOrder = "Place Order 🔒",
        reviewOrder = "Review Order",
        continueText = "Continue",
        address = "Delivery Address",
        paymentMethod = "Payment Method",
        secureCheckout = "Secure Checkout",
        purchases = "Purchases",
        sales = "Sales",
        purchaseHistory = "Purchase history",
        salesHistory = "Sales record",
        noPurchases = "You have no purchases yet",
        noSales = "There are no sales yet",
        totalSold = "Total sold"
    )
}
